# Generated by Django 4.2.1 on 2023-05-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_producttitle_producttype_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='images', verbose_name='Background Image')),
                ('general_title', models.CharField(max_length=50, verbose_name='General Title 1')),
                ('general_subtitle', models.CharField(max_length=60, verbose_name='Subtitle')),
                ('title1', models.CharField(max_length=50, verbose_name='Title 1')),
                ('img2', models.ImageField(upload_to='images', verbose_name='Image')),
                ('subtitle', models.CharField(max_length=60, verbose_name='Subtitle')),
                ('text1', models.TextField(verbose_name='Text 1')),
                ('text2', models.TextField(verbose_name='Text 2')),
                ('social1', models.CharField(max_length=50, verbose_name='Social 1')),
                ('social2', models.CharField(max_length=50, verbose_name='Social 2')),
                ('social3', models.CharField(max_length=50, verbose_name='Social 3')),
                ('social4', models.CharField(max_length=50, verbose_name='Social 4')),
                ('social_url1', models.URLField(verbose_name='Social Url 1')),
                ('social_url2', models.URLField(verbose_name='Social Url 2')),
                ('social_url3', models.URLField(verbose_name='Social Url 3')),
                ('social_url4', models.URLField(verbose_name='Social Url 4')),
                ('title2', models.CharField(max_length=50, verbose_name='Title 2')),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
    ]
