# Generated by Django 4.2.1 on 2023-05-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Background Image')),
                ('general_title', models.CharField(max_length=50, verbose_name='General Title 1')),
                ('general_subtitle', models.CharField(max_length=60, verbose_name='Subtitle')),
                ('title1', models.CharField(max_length=50, verbose_name='Title 1')),
                ('subtitle1', models.CharField(max_length=60, verbose_name='Subtitle 1')),
                ('text1', models.TextField(verbose_name='Text 1')),
                ('text2', models.TextField(verbose_name='Text 2')),
                ('social1', models.CharField(max_length=50, verbose_name='Social 1')),
                ('social2', models.CharField(max_length=50, verbose_name='Social 2')),
                ('social3', models.CharField(max_length=50, verbose_name='Social 3')),
                ('social4', models.CharField(max_length=50, verbose_name='Social 4')),
                ('social_url1', models.URLField(verbose_name='Social Url 1')),
                ('social_url2', models.URLField(verbose_name='Social Url 2')),
                ('social_url3', models.URLField(verbose_name='Social Url 3')),
                ('social_url4', models.URLField(verbose_name='Social Url 4')),
                ('title2', models.CharField(max_length=50, verbose_name='Title 2')),
                ('btn_name', models.CharField(max_length=40, verbose_name='Button Name')),
                ('title3', models.CharField(max_length=50, verbose_name='Title 3')),
                ('inp1', models.ImageField(max_length=50, upload_to='', verbose_name='Placeholder 1')),
                ('inp2', models.ImageField(max_length=50, upload_to='', verbose_name='Placeholder 2')),
                ('inp3', models.ImageField(max_length=50, upload_to='', verbose_name='Placeholder 3')),
                ('inp4', models.ImageField(max_length=50, upload_to='', verbose_name='Placeholder 4')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('text1', models.TextField(verbose_name='Text 1')),
                ('text2', models.TextField(verbose_name='Text 2')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=60, verbose_name='Username')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact POST',
                'verbose_name_plural': 'Contact POST',
            },
        ),
    ]
