# Generated by Django 4.2.1 on 2023-05-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_contact_contactinfo_contactpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contact'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subtitle1',
        ),
        migrations.AddField(
            model_name='contact',
            name='subtitle',
            field=models.CharField(default=1, max_length=60, verbose_name='Subtitle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='general_title',
            field=models.CharField(max_length=50, verbose_name='General Title'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='inp1',
            field=models.CharField(max_length=50, verbose_name='Placeholder 1'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='inp2',
            field=models.CharField(max_length=50, verbose_name='Placeholder 2'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='inp3',
            field=models.CharField(max_length=50, verbose_name='Placeholder 3'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='inp4',
            field=models.CharField(max_length=50, verbose_name='Placeholder 4'),
        ),
    ]
