# Generated by Django 4.2.1 on 2023-05-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='ProductTitle',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
