# Generated by Django 4.2.1 on 2023-05-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_product_category_delete_producttitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=50, verbose_name='Subtitle')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
            ],
        ),
    ]
